### ISSUE TITLE
does this run on linux/macos?

### ISSUE THREAD

**Issue by mreinstein** [electron/rcedit#112]
I'm assuming this only runs on windows? It'd be great to be able to run this from other platforms.

**Comment by Joseph-DiGiovanni** [comment]
According to #4 it relies on Windows APIs to parse exe files. It appears to work with wine on linux. If you use an arch based distro I've made it available as a package via the [AUR](https://aur.archlinux.org/packages/rcedit-bin).

Otherwise just download the rcedit exe, install wine and run it in terminal like this:
`wine "~/Downloads/rcedit-x64.exe" "/path/to/file.exe --options"`
